version: '{build}'
skip_tags: true

install:
  - git clone https://github.com/Fluorohydride/ygopro-scripts
  - cp -rf ygopro-scripts/constant.lua DataEditorX/data
  - git clone --branch link https://github.com/mercury233/ygopro
  - cp -rf ygopro/strings.conf DataEditorX/data

configuration: Release

build: 
    project: DataEditorX.sln
    parallel: true

after_build:
  - 7z a DataEditorX.7z win32 -xr!.git*

test: off

artifacts:
  - path: DataEditorX.7z
    name: DataEditorX
    
